import { findRequest, mapCollectionRequests } from '../core/collectionUtils';
import {
  AUTO_GENERATED_COLLECTION_ID,
  Collection,
  CollectionRequest,
  Endpoint,
  ScanSummary,
} from '../core/types';
import { EnvironmentManager } from '../environment/EnvironmentManager';
import {
  buildAutoGeneratedCollection,
  createEmptyAutoGeneratedCollection,
  createEmptyUserCollection,
  duplicateCollection,
  hasUnsavedModifications,
  validateCollectionName,
} from './ScanMerger';
import {
  buildCollectionExportDocument,
  materializeImportedCollection,
  resolveImportedCollectionName,
  type CollectionExportDocument,
} from './collectionImportExport';
import { collectFolderDeleteStats } from '../storage/treeOperations';
import {
  deleteCollectionFile,
  deleteFolderFromStorage,
  deleteRequestFromStorage,
  createFolderInStorage,
  createRequestInStorage,
  duplicateCollectionStorage,
  duplicateRequestInStorage,
  loadAllCollections,
  loadCollection,
  loadConfig,
  moveTreeNodeInStorage,
  nextUserCollectionId,
  renameCollectionMetadata,
  renameFolderInStorage,
  reorderTreeNodeInStorage,
  saveCollection,
  saveConfig,
  saveLastScan,
  updateRequestFile,
} from '../storage/ApiScopeStorage';

export class CollectionManager {
  constructor(private readonly envManager: EnvironmentManager) {}

  load(workspaceRoot: string): Collection[] {
    const collections = loadAllCollections(workspaceRoot);
    if (!collections.some((c) => c.id === AUTO_GENERATED_COLLECTION_ID)) {
      const empty = createEmptyAutoGeneratedCollection();
      saveCollection(workspaceRoot, empty);
      collections.unshift(empty);
    }
    return collections;
  }

  getAutoGenerated(collections: Collection[]): Collection | undefined {
    return collections.find((c) => c.id === AUTO_GENERATED_COLLECTION_ID);
  }

  needsRescanConfirmation(collections: Collection[]): boolean {
    return hasUnsavedModifications(this.getAutoGenerated(collections));
  }

  async applyScan(
    workspaceRoot: string,
    collections: Collection[],
    endpoints: Endpoint[],
    framework = 'spring'
  ): Promise<{ collections: Collection[]; summary: ScanSummary }> {
    const buildUrl = (p: string) => this.envManager.buildRequestUrl(p);

    const existing = this.getAutoGenerated(collections);
    const { collection, summary, lastScan } = buildAutoGeneratedCollection(
      endpoints,
      buildUrl,
      existing,
      workspaceRoot,
      framework
    );

    saveCollection(workspaceRoot, collection);
    saveLastScan(workspaceRoot, lastScan);

    const config = loadConfig(workspaceRoot);
    saveConfig(workspaceRoot, { ...config, lastScan: lastScan.lastScan });

    const updated = collections.filter((c) => c.id !== AUTO_GENERATED_COLLECTION_ID);
    updated.unshift(collection);
    return { collections: updated, summary };
  }

  duplicateCollection(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string
  ): { collections: Collection[]; copy: Collection } {
    const source = collections.find((c) => c.id === collectionId);
    if (!source) {
      return { collections, copy: createEmptyAutoGeneratedCollection() };
    }
    const newId = nextUserCollectionId(workspaceRoot);
    const copy = duplicateCollectionStorage(
      workspaceRoot,
      source,
      newId,
      duplicateCollection(source, collections.map((c) => c.name), newId).name
    );
    return { collections: [...collections, copy], copy };
  }

  createCollection(
    workspaceRoot: string,
    collections: Collection[],
    name?: string
  ): { collections: Collection[]; collection?: Collection; error?: string } {
    const newId = nextUserCollectionId(workspaceRoot);
    let collection: Collection;

    if (name !== undefined) {
      const trimmed = name.trim();
      const error = validateCollectionName(trimmed);
      if (error) {
        return { collections, error };
      }
      if (collections.some((c) => c.name.toLowerCase() === trimmed.toLowerCase())) {
        return { collections, error: 'A collection with this name already exists.' };
      }
      collection = { ...createEmptyUserCollection([], newId), name: trimmed };
    } else {
      collection = createEmptyUserCollection(
        collections.map((c) => c.name),
        newId
      );
    }

    saveCollection(workspaceRoot, collection);
    this.setActiveCollection(workspaceRoot, newId);
    return { collections: [...collections, collection], collection };
  }

  deleteCollection(workspaceRoot: string, collections: Collection[], collectionId: string): Collection[] {
    if (collectionId === AUTO_GENERATED_COLLECTION_ID) {
      return collections;
    }
    deleteCollectionFile(workspaceRoot, collectionId);
    const updated = collections.filter((c) => c.id !== collectionId);
    const config = loadConfig(workspaceRoot);
    if (config.activeCollectionId === collectionId) {
      saveConfig(workspaceRoot, {
        ...config,
        activeCollectionId: AUTO_GENERATED_COLLECTION_ID,
      });
    }
    return updated;
  }

  renameCollection(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    name: string
  ): { collections: Collection[]; error?: string } {
    const error = validateCollectionName(name);
    if (error) {
      return { collections, error };
    }
    const trimmed = name.trim();
    const target = collections.find((c) => c.id === collectionId);
    if (!target || target.type !== 'user') {
      return { collections, error: 'Only user collections can be renamed.' };
    }
    const updatedAt = new Date().toISOString();
    renameCollectionMetadata(workspaceRoot, collectionId, trimmed, updatedAt);
    const updated = collections.map((c) =>
      c.id === collectionId ? { ...c, name: trimmed, updatedAt } : c
    );
    return { collections: updated };
  }

  updateRequest(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    requestId: string,
    patch: Partial<CollectionRequest>
  ): Collection[] {
    const target = collections.find((c) => c.id === collectionId);
    if (!target) {
      return collections;
    }
    const updated = updateRequestFile(workspaceRoot, collectionId, requestId, patch);
    if (!updated) {
      return collections;
    }
    const next: Collection = {
      ...mapCollectionRequests(target, (req) =>
        req.id === requestId ? updated : req
      ),
      updatedAt: new Date().toISOString(),
      isDirty: target.type === 'generated' ? true : target.isDirty,
    };
    return collections.map((c) => (c.id === collectionId ? next : c));
  }

  deleteRequest(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    requestId: string
  ): Collection[] {
    const target = collections.find((c) => c.id === collectionId);
    if (!target) {
      return collections;
    }
    deleteRequestFromStorage(workspaceRoot, collectionId, requestId);
    const reloaded = loadCollection(workspaceRoot, collectionId);
    if (!reloaded) {
      return collections;
    }
    return collections.map((c) => (c.id === collectionId ? reloaded : c));
  }

  duplicateRequestInCollection(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    requestId: string
  ): { collections: Collection[]; copyId?: string } {
    const found = findRequest(collections, requestId);
    if (!found || found.collection.id !== collectionId) {
      return { collections };
    }
    const copyId = `req-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    duplicateRequestInStorage(
      workspaceRoot,
      collectionId,
      found.request,
      found.controllerName,
      copyId
    );
    const reloaded = loadCollection(workspaceRoot, collectionId);
    return {
      collections: reloaded
        ? collections.map((c) => (c.id === collectionId ? reloaded : c))
        : collections,
      copyId,
    };
  }

  findRequest(collections: Collection[], requestId: string) {
    return findRequest(collections, requestId);
  }

  setActiveCollection(workspaceRoot: string, collectionId: string): void {
    const config = loadConfig(workspaceRoot);
    saveConfig(workspaceRoot, { ...config, activeCollectionId: collectionId });
  }

  private replaceCollection(
    collections: Collection[],
    collection: Collection
  ): Collection[] {
    return collections.map((c) => (c.id === collection.id ? collection : c));
  }

  createFolder(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    parentFolderId: string | null,
    name: string
  ): { collections: Collection[]; error?: string; folderId?: string } {
    const { collection, error } = createFolderInStorage(
      workspaceRoot,
      collectionId,
      parentFolderId,
      name
    );
    if (error || !collection) {
      return { collections, error };
    }
    return { collections: this.replaceCollection(collections, collection) };
  }

  createRequest(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    parentFolderId: string | null,
    name?: string
  ): { collections: Collection[]; error?: string; requestId?: string } {
    const target = collections.find((c) => c.id === collectionId);
    if (!target || target.type === 'generated') {
      return { collections, error: 'Cannot create requests in the generated collection.' };
    }
    const { collection, requestId, error } = createRequestInStorage(
      workspaceRoot,
      collectionId,
      parentFolderId,
      name
    );
    if (error || !collection || !requestId) {
      return { collections, error };
    }
    return {
      collections: this.replaceCollection(collections, collection),
      requestId,
    };
  }

  renameFolder(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    folderId: string,
    name: string
  ): { collections: Collection[]; error?: string } {
    const { collection, error } = renameFolderInStorage(
      workspaceRoot,
      collectionId,
      folderId,
      name
    );
    if (error || !collection) {
      return { collections, error };
    }
    return { collections: this.replaceCollection(collections, collection) };
  }

  getFolderDeleteStats(
    collections: Collection[],
    collectionId: string,
    folderId: string
  ): { folderName: string; requestCount: number; subfolderCount: number } | undefined {
    const col = collections.find((c) => c.id === collectionId);
    const node = col?.tree.nodes[folderId];
    if (!col || !node) {
      return undefined;
    }
    const stats = collectFolderDeleteStats(col.tree, folderId);
    return {
      folderName: node.name,
      requestCount: stats.requestCount,
      subfolderCount: stats.subfolderCount,
    };
  }

  deleteFolder(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    folderId: string
  ): { collections: Collection[]; error?: string } {
    const { collection, error } = deleteFolderFromStorage(
      workspaceRoot,
      collectionId,
      folderId
    );
    if (error || !collection) {
      return { collections, error };
    }
    return { collections: this.replaceCollection(collections, collection) };
  }

  moveTreeNode(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    nodeId: string,
    nodeType: 'folder' | 'request',
    targetFolderId: string | null,
    insertBeforeId?: string
  ): { collections: Collection[]; error?: string } {
    const { collection, error } = moveTreeNodeInStorage(
      workspaceRoot,
      collectionId,
      nodeId,
      nodeType,
      targetFolderId,
      insertBeforeId
    );
    if (error || !collection) {
      return { collections, error };
    }
    return { collections: this.replaceCollection(collections, collection) };
  }

  reorderTreeNode(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    parentFolderId: string | null,
    nodeId: string,
    nodeType: 'folder' | 'request',
    insertBeforeId?: string
  ): { collections: Collection[]; error?: string } {
    const { collection, error } = reorderTreeNodeInStorage(
      workspaceRoot,
      collectionId,
      parentFolderId,
      nodeId,
      nodeType,
      insertBeforeId
    );
    if (error || !collection) {
      return { collections, error };
    }
    return { collections: this.replaceCollection(collections, collection) };
  }

  renameRequest(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    requestId: string,
    name: string
  ): { collections: Collection[]; error?: string } {
    const trimmed = name.trim();
    if (!trimmed) {
      return { collections, error: 'Request name cannot be empty.' };
    }
    const updated = updateRequestFile(workspaceRoot, collectionId, requestId, {
      displayName: trimmed,
      displayNameOverride: true,
      name: trimmed,
    });
    if (!updated) {
      return { collections, error: 'Request not found.' };
    }
    const target = collections.find((c) => c.id === collectionId);
    if (!target) {
      return { collections };
    }
    const next: Collection = {
      ...mapCollectionRequests(target, (req) => (req.id === requestId ? updated : req)),
      updatedAt: new Date().toISOString(),
      isDirty: target.type === 'generated' ? true : target.isDirty,
    };
    return { collections: this.replaceCollection(collections, next) };
  }

  renameCollectionWithValidation(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string,
    name: string
  ): { collections: Collection[]; error?: string } {
    const error = validateCollectionName(name);
    if (error) {
      return { collections, error };
    }
    const trimmed = name.trim();
    const duplicate = collections.some(
      (c) => c.id !== collectionId && c.name.toLowerCase() === trimmed.toLowerCase()
    );
    if (duplicate) {
      return { collections, error: 'A collection with this name already exists.' };
    }
    return this.renameCollection(workspaceRoot, collections, collectionId, trimmed);
  }

  buildExportDocument(
    workspaceRoot: string,
    collections: Collection[],
    collectionId: string
  ): CollectionExportDocument | undefined {
    const collection =
      collections.find((c) => c.id === collectionId) ?? loadCollection(workspaceRoot, collectionId);
    if (!collection) {
      return undefined;
    }
    return buildCollectionExportDocument(collection, workspaceRoot);
  }

  importFromDocument(
    workspaceRoot: string,
    collections: Collection[],
    document: CollectionExportDocument
  ): {
    collections: Collection[];
    collection: Collection;
    renamed: boolean;
    finalName: string;
    originalName: string;
  } {
    const originalName = document.collection.name.trim();
    const finalName = resolveImportedCollectionName(
      originalName,
      collections.map((c) => c.name)
    );
    const newId = nextUserCollectionId(workspaceRoot);
    const imported = materializeImportedCollection(document, newId, finalName);
    saveCollection(workspaceRoot, imported);
    this.setActiveCollection(workspaceRoot, newId);
    return {
      collections: [...collections, imported],
      collection: imported,
      renamed: finalName !== originalName,
      finalName,
      originalName,
    };
  }
}
