import { normalizeSourceFile } from '../core/pathUtils';
import {
  AUTO_GENERATED_COLLECTION_ID,
  AUTO_GENERATED_COLLECTION_NAME,
  Collection,
  CollectionRequest,
  ControllerGroup,
  Endpoint,
  LastScanRecord,
  ScanSummary,
  requestSourceKey,
} from '../core/types';
import { countControllers, countEndpoints } from '../core/collectionUtils';
import { mergeScanIntoTree, controllersToTree, remapTreeRequestIds } from '../storage/treeAdapter';
import { buildExampleRequestBody } from '../request-executor/RequestBodyBuilder';
import type { CollectionRequest, Endpoint } from '../core/types';
import { buildDefaultHeaders } from '../request-executor/RequestExecutor';
import { resolveEndpointDisplayName } from '../core/requestDisplayName';

export function createEmptyAutoGeneratedCollection(): Collection {
  const now = new Date().toISOString();
  return {
    id: AUTO_GENERATED_COLLECTION_ID,
    name: AUTO_GENERATED_COLLECTION_NAME,
    type: 'generated',
    controllers: [],
    tree: { root: [], nodes: {} },
    createdAt: now,
    updatedAt: now,
    isDirty: false,
  };
}

export function createEmptyUserCollection(existingNames: string[], newId: string): Collection {
  const now = new Date().toISOString();
  const name = nextAvailableCollectionName(existingNames);
  return {
    id: newId,
    name,
    type: 'user',
    controllers: [],
    tree: { root: [], nodes: {} },
    createdAt: now,
    updatedAt: now,
    isDirty: false,
  };
}

export function buildAutoGeneratedCollection(
  endpoints: Endpoint[],
  buildUrl: (path: string) => string,
  existing?: Collection,
  workspaceRoot?: string,
  framework = 'spring'
): { collection: Collection; summary: ScanSummary; lastScan: LastScanRecord } {
  const now = new Date().toISOString();
  const oldByKey = new Map<string, CollectionRequest>();
  for (const group of existing?.controllers ?? []) {
    for (const req of group.requests) {
      if (req.sourceKey) {
        oldByKey.set(req.sourceKey, req);
      }
    }
  }

  const byController = new Map<string, CollectionRequest[]>();
  const newKeys = new Set<string>();
  const summary: ScanSummary = { added: [], updated: [], removed: [] };
  const addedRequests: Array<{ request: CollectionRequest; controllerName: string }> = [];
  const removedRequestIds: string[] = [];

  const sorted = [...endpoints].sort((a, b) => {
    const ctrl = a.controllerName.localeCompare(b.controllerName);
    if (ctrl !== 0) {
      return ctrl;
    }
    const pathCmp = a.path.localeCompare(b.path);
    return pathCmp !== 0 ? pathCmp : a.method.localeCompare(b.method);
  });

  for (const ep of sorted) {
    const key = requestSourceKey(ep.controllerName, ep.method, ep.path);
    newKeys.add(key);
    const label = `${ep.method} ${ep.path}`;
    const old = oldByKey.get(key);

    let request: CollectionRequest;
    if (!old) {
      summary.added.push(`+ ${label}`);
      request = endpointToRequest(ep, buildUrl, key, workspaceRoot, framework);
      addedRequests.push({ request, controllerName: ep.controllerName });
    } else {
      const newSourceFile = workspaceRoot
        ? normalizeSourceFile(workspaceRoot, undefined, ep.filePath)
        : ep.filePath;
      const sourceChanged =
        old.method !== ep.method ||
        old.path !== ep.path ||
        old.sourceFile !== newSourceFile ||
        old.filePath !== ep.filePath;
      const sourceLineChanged = old.sourceLine !== ep.line;

      if (sourceChanged) {
        summary.updated.push(`~ ${label}`);
      }

      const regeneratedBody = sourceChanged || sourceLineChanged
        ? buildExampleRequestBody(ep, framework)
        : undefined;

      request = {
        ...old,
        method: ep.method,
        path: ep.path,
        url: buildUrl(ep.path),
        sourceKey: key,
        sourceFile: newSourceFile,
        sourceLine: ep.line,
        filePath: ep.filePath,
        line: ep.line,
        ...(old.displayNameOverride
          ? {}
          : { displayName: resolveEndpointDisplayName(ep) }),
        ...(regeneratedBody ? applyGeneratedRequestBody(regeneratedBody) : {}),
      };
    }

    const list = byController.get(ep.controllerName) ?? [];
    list.push(request);
    byController.set(ep.controllerName, list);
  }

  for (const [key, old] of oldByKey) {
    if (!newKeys.has(key)) {
      summary.removed.push(`- ${old.method} ${old.path}`);
      removedRequestIds.push(old.id);
    }
  }

  const controllers: ControllerGroup[] = [...byController.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, requests]) => ({ name, requests }));

  const tree = mergeScanIntoTree(
    existing?.tree,
    controllers,
    removedRequestIds,
    addedRequests
  );

  const collection: Collection = {
    id: AUTO_GENERATED_COLLECTION_ID,
    name: AUTO_GENERATED_COLLECTION_NAME,
    type: 'generated',
    controllers,
    tree,
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
    isDirty: false,
  };

  const lastScan: LastScanRecord = {
    framework,
    controllers: countControllers(collection),
    endpoints: countEndpoints(collection),
    lastScan: now,
    added: summary.added.length,
    updated: summary.updated.length,
    removed: summary.removed.length,
    addedLabels: summary.added,
    updatedLabels: summary.updated,
    removedLabels: summary.removed,
  };

  return { collection, summary, lastScan };
}

function endpointToRequest(
  ep: Endpoint,
  buildUrl: (path: string) => string,
  sourceKey: string,
  workspaceRoot?: string,
  framework = 'spring'
): CollectionRequest {
  const sourceFile = workspaceRoot
    ? normalizeSourceFile(workspaceRoot, undefined, ep.filePath)
    : undefined;
  const generatedBody = buildExampleRequestBody(ep, framework);
  return {
    id: `req-${sourceKey.replace(/[^a-zA-Z0-9]+/g, '-')}`,
    displayName: resolveEndpointDisplayName(ep),
    method: ep.method,
    url: buildUrl(ep.path),
    headers: buildDefaultHeaders(),
    queryParams: [],
    path: ep.path,
    sourceKey,
    sourceFile,
    sourceLine: ep.line,
    filePath: ep.filePath,
    line: ep.line,
    ...applyGeneratedRequestBody(generatedBody),
  };
}

function applyGeneratedRequestBody(
  generated: ReturnType<typeof buildExampleRequestBody>
): Pick<CollectionRequest, 'body' | 'requestBody'> {
  if (!generated) {
    return {};
  }

  if (generated.requestBody) {
    const next: Pick<CollectionRequest, 'body' | 'requestBody'> = {
      requestBody: generated.requestBody,
    };
    if (generated.requestBody.kind === 'json' || generated.requestBody.kind === 'raw') {
      next.body = generated.requestBody.content;
    } else {
      next.body = undefined;
    }
    return next;
  }

  if (generated.body !== undefined) {
    return { body: generated.body };
  }

  return {};
}

export function duplicateCollection(
  source: Collection,
  existingNames: string[],
  newId: string
): Collection {
  const now = new Date().toISOString();
  let name = `${source.name} Copy`;
  let n = 2;
  while (existingNames.includes(name)) {
    name = `${source.name} Copy ${n}`;
    n++;
  }

  const idMap = new Map<string, string>();
  const controllers = source.controllers.map((g) => ({
    name: g.name,
    requests: g.requests.map((r) => {
      const newId = `req-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      idMap.set(r.id, newId);
      return {
        ...r,
        id: newId,
        sourceKey: undefined,
      };
    }),
  }));

  return {
    id: newId,
    name,
    type: 'user',
    controllers,
    tree: remapTreeRequestIds(source.tree ?? controllersToTree(source.controllers), idMap),
    createdAt: now,
    updatedAt: now,
    isDirty: false,
  };
}

export function duplicateRequest(
  source: CollectionRequest,
  controllerName: string,
  collection: Collection,
  copyId = `req-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
): { collection: Collection; copyId: string } {
  const copy: CollectionRequest = {
    ...source,
    id: copyId,
    sourceKey: undefined,
  };

  const controllers = collection.controllers.map((g) => {
    if (g.name !== controllerName) {
      return g;
    }
    const idx = g.requests.findIndex((r) => r.id === source.id);
    const requests = [...g.requests];
    if (idx >= 0) {
      requests.splice(idx + 1, 0, copy);
    } else {
      requests.push(copy);
    }
    return { ...g, requests };
  });

  return {
    collection: {
      ...collection,
      controllers,
      updatedAt: new Date().toISOString(),
      isDirty: collection.type === 'generated' ? true : collection.isDirty,
    },
    copyId,
  };
}

export function hasUnsavedModifications(collection: Collection | undefined): boolean {
  return Boolean(collection?.isDirty);
}

export function validateCollectionName(name: string): string | undefined {
  const trimmed = name.trim();
  if (!trimmed) {
    return 'Collection name cannot be empty.';
  }
  if (trimmed.length > 100) {
    return 'Collection name must be 100 characters or fewer.';
  }
  return undefined;
}

export function nextAvailableCollectionName(
  existingNames: string[],
  baseName = 'New Collection'
): string {
  let name = baseName;
  let n = 2;
  while (existingNames.some((existing) => existing.toLowerCase() === name.toLowerCase())) {
    name = `${baseName} ${n++}`;
  }
  return name;
}
