import * as vscode from 'vscode';
import { countEndpoints } from '../core/collectionUtils';
import { CollectionManager } from '../collections/CollectionManager';
import { Collection, CollectionRequest, HttpMethod } from '../core/types';
import { EnvironmentManager } from '../environment/EnvironmentManager';
import { getScannerForProject } from '../scanner/ScannerRegistry';
import { detectProjectFramework } from '../scanner/detectProjectFramework';
import { countCollectionRequests, countRequestsInFolder, findFolderParentId, findRequestParentId } from '../storage/treeOperations';
import { apiscopeExists, ensureApiscopeForCollections } from '../storage/ApiScopeStorage';
import { collectionTreeIcon, folderTreeIcon, methodTreeIcon } from './treeIcons';
import { resolveCollectionRequestDisplayName } from '../core/requestDisplayName';
import { projectDetectedTooltip } from '../core/projectLabel';

export class CollectionsTreeProvider implements vscode.TreeDataProvider<CollectionTreeItem> {
  private _onDidChangeTreeData = new vscode.EventEmitter<CollectionTreeItem | undefined>();
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event;
  private projectLabel = '';
  private projectDetected = false;
  private endpointCount = 0;
  private collections: Collection[] = [];
  private readonly collectionManager = new CollectionManager(new EnvironmentManager());

  getCollections(): Collection[] {
    return this.collections;
  }

  async refresh(options?: { initialize?: boolean }): Promise<void> {
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) {
      this.collections = [];
      this.projectLabel = '';
      this.projectDetected = false;
      this.endpointCount = 0;
      this._onDidChangeTreeData.fire(undefined);
      return;
    }

    const root = folder.uri.fsPath;
    if (options?.initialize) {
      ensureApiscopeForCollections(root);
    }

    const projectInfo = await detectProjectFramework(root);
    this.projectDetected = projectInfo.detected;
    this.projectLabel = projectInfo.detected
      ? projectInfo.label
      : 'No supported API framework detected';

    if (!apiscopeExists(root)) {
      this.collections = [];
      this.endpointCount = 0;
      this._onDidChangeTreeData.fire(undefined);
      return;
    }

    this.collections = this.collectionManager.load(root);

    const auto = this.collectionManager.getAutoGenerated(this.collections);
    this.endpointCount = auto ? countEndpoints(auto) : 0;

    if (projectInfo.detected && (!auto || this.endpointCount === 0)) {
      const scanner = await getScannerForProject(root);
      if (scanner) {
        const endpoints = await scanner.scan({ workspaceRoot: root });
        const envManager = new EnvironmentManager();
        await envManager.refreshGeneratedEnvironment(root);
        const { collections } = await this.collectionManager.applyScan(
          root,
          this.collections,
          endpoints,
          scanner.frameworkId
        );
        this.collections = collections;
        const refreshed = this.collectionManager.getAutoGenerated(this.collections);
        this.endpointCount = refreshed ? countEndpoints(refreshed) : 0;
      }
    }

    this._onDidChangeTreeData.fire(undefined);
  }

  getTreeItem(element: CollectionTreeItem): vscode.TreeItem {
    return element;
  }

  getChildren(element?: CollectionTreeItem): CollectionTreeItem[] {
    if (!element) {
      const items: CollectionTreeItem[] = [...this.buildTabNavItems()];

      if (this.projectLabel) {
        const infoLabel = `${this.projectLabel}${this.endpointCount ? ` · ${this.endpointCount}` : ''}`;
        const infoTooltip = this.projectDetected
          ? projectDetectedTooltip(this.projectLabel, this.endpointCount)
          : this.projectLabel;
        items.push(
          new CollectionTreeItem(
            infoLabel,
            vscode.TreeItemCollapsibleState.None,
            'info',
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            infoTooltip
          )
        );
      }
      if (!this.collections.length) {
        items.push(
          new CollectionTreeItem(
            'Run "Scan Endpoints" to generate collections',
            vscode.TreeItemCollapsibleState.None,
            'hint'
          )
        );
        return items;
      }
      for (const col of this.collections) {
        items.push(this.buildCollectionTreeItem(col));
      }
      return items;
    }

    if (element.kind === 'collection') {
      const col = this.collections.find((c) => c.id === element.collectionId);
      if (!col) {
        return [];
      }
      return this.treeRefsToItems(col, col.tree.root, null);
    }

    if (element.kind === 'folder') {
      const col = this.collections.find((c) => c.id === element.collectionId);
      const node = col?.tree.nodes[element.folderId!];
      if (!col || !node) {
        return [];
      }
      const refs = node.children.map((id) => ({
        id,
        type: col.tree.nodes[id] ? ('folder' as const) : ('request' as const),
      }));
      return this.treeRefsToItems(col, refs, element.folderId!);
    }

    return [];
  }

  getParent(element: CollectionTreeItem): CollectionTreeItem | undefined {
    if (
      element.kind === 'info' ||
      element.kind === 'hint' ||
      element.kind === 'collection' ||
      element.kind === 'nav'
    ) {
      return undefined;
    }
    if (!element.collectionId) {
      return undefined;
    }
    const col = this.collections.find((c) => c.id === element.collectionId);
    if (!col) {
      return undefined;
    }
    if (element.kind === 'request' && element.request) {
      const parentFolderId = findRequestParentId(col.tree, element.request.id);
      if (parentFolderId) {
        return this.buildFolderTreeItem(col, parentFolderId);
      }
      return this.buildCollectionTreeItem(col);
    }
    if (element.kind === 'folder' && element.folderId) {
      const parentFolderId = findFolderParentId(col.tree, element.folderId);
      if (parentFolderId) {
        return this.buildFolderTreeItem(col, parentFolderId);
      }
      return this.buildCollectionTreeItem(col);
    }
    return undefined;
  }

  private treeRefsToItems(
    col: Collection,
    refs: Array<{ id: string; type: 'folder' | 'request' }>,
    _parentFolderId: string | null
  ): CollectionTreeItem[] {
    const requestMap = new Map<string, CollectionRequest>();
    for (const group of col.controllers) {
      for (const req of group.requests) {
        requestMap.set(req.id, req);
      }
    }

    return refs.flatMap((ref) => {
      if (ref.type === 'folder') {
        const item = this.buildFolderTreeItem(col, ref.id);
        return item ? [item] : [];
      }

      const req = requestMap.get(ref.id);
      if (!req) {
        return [];
      }
      return [this.buildRequestTreeItem(col, req)];
    });
  }

  getRequestTreeItem(collectionId: string, requestId: string): CollectionTreeItem | undefined {
    const col = this.collections.find((c) => c.id === collectionId);
    if (!col) {
      return undefined;
    }
    for (const group of col.controllers) {
      const req = group.requests.find((r) => r.id === requestId);
      if (req) {
        return this.buildRequestTreeItem(col, req);
      }
    }
    return undefined;
  }

  private buildTabNavItems(): CollectionTreeItem[] {
    return [
      new CollectionTreeItem('Environments', vscode.TreeItemCollapsibleState.None, 'nav', 'environments'),
      new CollectionTreeItem(
        'Global Authentication',
        vscode.TreeItemCollapsibleState.None,
        'nav',
        'login'
      ),
      new CollectionTreeItem('History', vscode.TreeItemCollapsibleState.None, 'nav', 'history'),
      new CollectionTreeItem('Scan', vscode.TreeItemCollapsibleState.None, 'nav', 'scan'),
    ];
  }

  private buildCollectionTreeItem(col: Collection): CollectionTreeItem {
    const count = countCollectionRequests(col.tree);
    const hasChildren = col.tree.root.length > 0;
    return new CollectionTreeItem(
      col.name,
      hasChildren
        ? vscode.TreeItemCollapsibleState.Collapsed
        : vscode.TreeItemCollapsibleState.None,
      'collection',
      undefined,
      col.id,
      col.type,
      undefined,
      undefined,
      String(count)
    );
  }

  private buildFolderTreeItem(col: Collection, folderId: string): CollectionTreeItem | undefined {
    const node = col.tree.nodes[folderId];
    if (!node) {
      return undefined;
    }
    const count = countRequestsInFolder(col.tree, folderId);
    const hasChildren = node.children.length > 0;
    return new CollectionTreeItem(
      node.name,
      hasChildren
        ? vscode.TreeItemCollapsibleState.Collapsed
        : vscode.TreeItemCollapsibleState.None,
      'folder',
      undefined,
      col.id,
      col.type,
      folderId,
      undefined,
      String(count)
    );
  }

  private buildRequestTreeItem(col: Collection, req: CollectionRequest): CollectionTreeItem {
    const displayName = resolveCollectionRequestDisplayName(req);
    return new CollectionTreeItem(
      displayName,
      vscode.TreeItemCollapsibleState.None,
      'request',
      undefined,
      col.id,
      col.type,
      undefined,
      req
    );
  }
}

export type CollectionTreeKind =
  | 'nav'
  | 'info'
  | 'hint'
  | 'collection'
  | 'folder'
  | 'request';

export type NavTabId = 'environments' | 'login' | 'history' | 'scan';

export class CollectionTreeItem extends vscode.TreeItem {
  constructor(
    public readonly label: string,
    public readonly collapsibleState: vscode.TreeItemCollapsibleState,
    public readonly kind: CollectionTreeKind,
    public readonly navId?: NavTabId,
    public readonly collectionId?: string,
    public readonly collectionType?: 'generated' | 'user',
    public readonly folderId?: string,
    public readonly request?: CollectionRequest,
    public readonly countLabel?: string,
    tooltipText?: string
  ) {
    super(label, collapsibleState);

    if (countLabel) {
      this.description = countLabel;
    }

    if (tooltipText) {
      this.tooltip = tooltipText;
    }

    if (kind === 'nav' && navId) {
      this.id = `apiScope:nav:${navId}`;
      const navConfig = NAV_TAB_CONFIG[navId];
      this.iconPath = new vscode.ThemeIcon(navConfig.icon);
      this.command = {
        command: navConfig.command,
        title: navConfig.title,
      };
      this.contextValue = `apiScope.nav.${navId}`;
    } else if (kind === 'request' && request) {
      this.id = `${collectionId}:${request.id}`;
      this.command = {
        command: 'apiScope.open',
        title: 'Open in APIScope',
        arguments: [request.id],
      };
      this.iconPath = methodTreeIcon(request.method as HttpMethod);
      this.tooltip = `${request.method} ${request.path}\n${resolveCollectionRequestDisplayName(request)}`;
      this.contextValue = request.sourceKey ? 'apiScope.request.scanned' : 'apiScope.request';
    } else if (kind === 'collection') {
      this.id = collectionId;
      this.iconPath = collectionTreeIcon(collectionType === 'generated');
      this.contextValue =
        collectionType === 'generated' ? 'apiScope.collection.generated' : 'apiScope.collection.user';
      if (collectionType === 'generated') {
        this.tooltip = 'Generated Collection — refreshed from source scan';
      }
    } else if (kind === 'folder') {
      this.id = `${collectionId}:${folderId}`;
      this.iconPath = folderTreeIcon(
        collapsibleState === vscode.TreeItemCollapsibleState.Expanded
      );
      this.contextValue =
        collectionType === 'generated' ? 'apiScope.folder.generated' : 'apiScope.folder.user';
    } else if (kind === 'info') {
      this.iconPath = new vscode.ThemeIcon('info', new vscode.ThemeColor('apiScope.statusInfo'));
    } else if (kind === 'hint') {
      this.iconPath = new vscode.ThemeIcon('lightbulb', new vscode.ThemeColor('apiScope.statusHint'));
    }
  }
}

const NAV_TAB_CONFIG: Record<
  NavTabId,
  { icon: string; command: string; title: string }
> = {
  environments: {
    icon: 'layers',
    command: 'apiScope.openEnvironmentsTab',
    title: 'Open Environments',
  },
  login: {
    icon: 'shield',
    command: 'apiScope.openLoginTab',
    title: 'Open Global Authentication',
  },
  history: {
    icon: 'history',
    command: 'apiScope.openHistoryTab',
    title: 'Open History',
  },
  scan: {
    icon: 'search',
    command: 'apiScope.openScanTab',
    title: 'Open Scan',
  },
};
