import * as path from 'path';
import { countEndpoints } from '../src/core/collectionUtils';
import { CollectionManager } from '../src/collections/CollectionManager';
import { AUTO_GENERATED_COLLECTION_NAME } from '../src/core/types';
import { EnvironmentManager } from '../src/environment/EnvironmentManager';
import { SpringScanner } from '../src/spring-scanner/SpringScanner';
import { detectBaseUrl } from '../src/spring-scanner/SpringBaseUrlDetector';
import { loadLastScan } from '../src/storage/ApiScopeStorage';

const sampleRoot = path.join(__dirname, '..', 'sample-projects', 'spring-demo');

async function main() {
  const scanner = new SpringScanner();
  const endpoints = await scanner.scan({ workspaceRoot: sampleRoot });
  const envManager = new EnvironmentManager();
  const collectionManager = new CollectionManager(envManager);
  const collections = collectionManager.load(sampleRoot);
  const { collections: updated } = await collectionManager.applyScan(
    sampleRoot,
    collections,
    endpoints,
    scanner.frameworkId
  );
  const collection = collectionManager.getAutoGenerated(updated)!;
  const lastScan = loadLastScan(sampleRoot);
  const baseUrl = detectBaseUrl(sampleRoot);

  console.log('Base URL:', baseUrl);
  console.log('Collection:', collection.name);
  console.log('Type:', collection.type);
  console.log('Requests:', countEndpoints(collection));

  for (const group of collection.controllers) {
    console.log(`\n  ${group.name}:`);
    for (const req of group.requests) {
      console.log(`    ${req.method} ${req.path}`);
    }
  }

  if (collection.name !== AUTO_GENERATED_COLLECTION_NAME) {
    console.error('Expected collection name "Generated Collection"');
    process.exit(1);
  }

  const expected = [
    'GET /users',
    'GET /users/{id}',
    'POST /users',
    'PUT /users/{id}',
    'DELETE /users/{id}',
    'GET /users/search',
  ];
  const actual = collection.controllers
    .flatMap((g) => g.requests)
    .map((e) => `${e.method} ${e.path}`)
    .sort();
  const missing = expected.filter((e) => !actual.includes(e));
  if (missing.length) {
    console.error('\nMissing endpoints:', missing);
    process.exit(1);
  }
  if (baseUrl !== 'http://localhost:8085') {
    console.error('Expected baseUrl http://localhost:8085, got', baseUrl);
    process.exit(1);
  }
  if (!lastScan) {
    console.error('Expected last-scan.json');
    process.exit(1);
  }

  console.log('\nLast scan:', lastScan);
  console.log('\nScan validation passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
