import * as path from 'path';
import { countEndpoints } from '../src/core/collectionUtils';
import { CollectionManager } from '../src/collections/CollectionManager';
import { AUTO_GENERATED_COLLECTION_NAME } from '../src/core/types';
import { EnvironmentManager } from '../src/environment/EnvironmentManager';
import { ExpressScanner } from '../src/express-scanner/ExpressScanner';
import { detectExpressBaseUrl } from '../src/express-scanner/ExpressBaseUrlDetector';
import { loadLastScan } from '../src/storage/ApiScopeStorage';

const sampleRoot = path.join(__dirname, '..', 'sample-projects', 'files-api-nodejs');

async function main() {
  const scanner = new ExpressScanner();
  const canScan = await scanner.canScan(sampleRoot);
  if (!canScan) {
    console.error('Express project not detected for files-api-nodejs sample');
    process.exit(1);
  }

  const endpoints = await scanner.scan({ workspaceRoot: sampleRoot });
  const envManager = new EnvironmentManager();
  await envManager.refreshGeneratedEnvironment(sampleRoot);
  const collectionManager = new CollectionManager(envManager);
  const collections = collectionManager.load(sampleRoot);
  const { collections: updated } = await collectionManager.applyScan(
    sampleRoot,
    collections,
    endpoints,
    scanner.frameworkId
  );
  const collection = collectionManager.getAutoGenerated(updated)!;
  const lastScan = loadLastScan(sampleRoot);
  const baseUrl = detectExpressBaseUrl(sampleRoot);

  console.log('Base URL:', baseUrl);
  console.log('Collection:', collection.name);
  console.log('Type:', collection.type);
  console.log('Requests:', countEndpoints(collection));

  for (const group of collection.controllers) {
    console.log(`\n  ${group.name}:`);
    for (const req of group.requests) {
      console.log(`    ${req.method} ${req.path}`);
    }
  }

  if (collection.name !== AUTO_GENERATED_COLLECTION_NAME) {
    console.error('Expected collection name "Generated Collection"');
    process.exit(1);
  }

  const expected = [
    'GET /download/blob',
    'GET /download/image',
    'GET /download/json',
    'GET /download/pdf',
    'GET /download/slow',
    'GET /download/text',
    'GET /download/zip',
    'GET /health',
    'POST /upload/multiple',
    'POST /upload/single',
  ];
  const actual = collection.controllers
    .flatMap((g) => g.requests)
    .map((e) => `${e.method} ${e.path}`)
    .sort();
  const missing = expected.filter((e) => !actual.includes(e));
  if (missing.length) {
    console.error('\nMissing endpoints:', missing);
    console.error('Actual:', actual);
    process.exit(1);
  }
  if (baseUrl !== 'http://localhost:3001') {
    console.error('Expected baseUrl http://localhost:3001, got', baseUrl);
    process.exit(1);
  }
  if (!lastScan || lastScan.framework !== 'express') {
    console.error('Expected last-scan.json with framework express');
    process.exit(1);
  }

  console.log('\nLast scan:', lastScan);
  console.log('\nExpress scan validation passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
