import * as path from 'path';
import { countEndpoints } from '../src/core/collectionUtils';
import { CollectionManager } from '../src/collections/CollectionManager';
import { AUTO_GENERATED_COLLECTION_NAME } from '../src/core/types';
import { EnvironmentManager } from '../src/environment/EnvironmentManager';
import { FastApiScanner } from '../src/fastapi-scanner/FastApiScanner';
import { detectFastApiBaseUrl } from '../src/fastapi-scanner/FastApiBaseUrlDetector';
import { loadLastScan } from '../src/storage/ApiScopeStorage';

const sampleRoot = path.join(__dirname, '..', 'sample-projects', 'jwt-api-fastapi');

async function main() {
  const scanner = new FastApiScanner();
  const canScan = await scanner.canScan(sampleRoot);
  if (!canScan) {
    console.error('FastAPI project not detected for jwt-api-fastapi sample');
    process.exit(1);
  }

  const endpoints = await scanner.scan({ workspaceRoot: sampleRoot });
  const envManager = new EnvironmentManager();
  await envManager.refreshGeneratedEnvironment(sampleRoot);
  const collectionManager = new CollectionManager(envManager);
  const collections = collectionManager.load(sampleRoot);
  const { collections: updated } = await collectionManager.applyScan(
    sampleRoot,
    collections,
    endpoints,
    scanner.frameworkId
  );
  const collection = collectionManager.getAutoGenerated(updated)!;
  const lastScan = loadLastScan(sampleRoot);
  const baseUrl = detectFastApiBaseUrl(sampleRoot);

  console.log('Base URL:', baseUrl);
  console.log('Collection:', collection.name);
  console.log('Type:', collection.type);
  console.log('Requests:', countEndpoints(collection));

  for (const group of collection.controllers) {
    console.log(`\n  ${group.name}:`);
    for (const req of group.requests) {
      console.log(`    ${req.method} ${req.path}`);
    }
  }

  if (collection.name !== AUTO_GENERATED_COLLECTION_NAME) {
    console.error('Expected collection name "Generated Collection"');
    process.exit(1);
  }

  const expected = [
    'GET /auth/me',
    'GET /health',
    'GET /private',
    'GET /public',
    'POST /auth/login',
  ];
  const actual = collection.controllers
    .flatMap((g) => g.requests)
    .map((e) => `${e.method} ${e.path}`)
    .sort();
  const missing = expected.filter((e) => !actual.includes(e));
  if (missing.length) {
    console.error('\nMissing endpoints:', missing);
    console.error('Actual:', actual);
    process.exit(1);
  }
  if (baseUrl !== 'http://localhost:8000') {
    console.error('Expected baseUrl http://localhost:8000, got', baseUrl);
    process.exit(1);
  }
  if (!lastScan || lastScan.framework !== 'fastapi') {
    console.error('Expected last-scan.json with framework fastapi');
    process.exit(1);
  }

  console.log('\nLast scan:', lastScan);
  console.log('\nFastAPI scan validation passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
